apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/gateway.bessystem.com_authenticationfilters.yaml
  - bases/gateway.bessystem.com_clientsettingspolicies.yaml
  - bases/gateway.bessystem.com_bwsgateways.yaml
  - bases/gateway.bessystem.com_bwsproxies.yaml
  - bases/gateway.bessystem.com_observabilitypolicies.yaml
  - bases/gateway.bessystem.com_proxysettingspolicies.yaml
  - bases/gateway.bessystem.com_snippetsfilters.yaml
  - bases/gateway.bessystem.com_snippetspolicies.yaml
  - bases/gateway.bessystem.com_upstreamsettingspolicies.yaml
  - bases/gateway.bessystem.com_ratelimitpolicies.yaml
