load_module modules/ngx_http_js_module.so;
include /etc/bws/main-includes/*.conf;

worker_processes auto;

pid /var/run/bws/bws.pid;

events {
  include /etc/bws/events-includes/*.conf;
}

http {
  include /etc/bws/mime.types;
  js_import modules/njs/httpmatches.js;
  js_import modules/njs/epp.js;

  default_type application/octet-stream;

  proxy_headers_hash_bucket_size 512;
  proxy_headers_hash_max_size 1024;
  server_names_hash_bucket_size 512;
  server_names_hash_max_size 1024;
  variables_hash_bucket_size 512;
  variables_hash_max_size 1024;
  map_hash_bucket_size 512;
  map_hash_max_size 2048;

  sendfile on;
  tcp_nopush on;

  include /etc/bws/conf.d/*.conf;
}

stream {
  variables_hash_bucket_size 512;
  variables_hash_max_size 1024;

  map_hash_max_size 2048;
  map_hash_bucket_size 256;

  log_format stream-main '$remote_addr [$time_local] '
                         '$protocol $status $bytes_sent $bytes_received '
                         '$session_time "$ssl_preread_server_name"';
  access_log /dev/stdout stream-main;
  include /etc/bws/stream-conf.d/*.conf;
}
